// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZpLL5ht_HMm5nEB_-i0TXVfn5B_5lJMU',
    appId: '1:896018341442:web:6e55f3dd76101d44edd7db',
    messagingSenderId: '896018341442',
    projectId: 'stockbuddy-33948',
    authDomain: 'stockbuddy-33948.firebaseapp.com',
    storageBucket: 'stockbuddy-33948.firebasestorage.app',
    measurementId: 'G-SSQ2TF5XWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNLG2W0zF7MN7py0U19KMsIQ_Ot6GTTus',
    appId: '1:896018341442:android:171be8cca41d8cb1edd7db',
    messagingSenderId: '896018341442',
    projectId: 'stockbuddy-33948',
    storageBucket: 'stockbuddy-33948.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKtAoU_3-kjzZEWuA7Zs_8kDGMk4zjfJs',
    appId: '1:896018341442:ios:5ec32a88e2d0e288edd7db',
    messagingSenderId: '896018341442',
    projectId: 'stockbuddy-33948',
    storageBucket: 'stockbuddy-33948.firebasestorage.app',
    iosBundleId: 'com.client.stockbuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKtAoU_3-kjzZEWuA7Zs_8kDGMk4zjfJs',
    appId: '1:896018341442:ios:5ec32a88e2d0e288edd7db',
    messagingSenderId: '896018341442',
    projectId: 'stockbuddy-33948',
    storageBucket: 'stockbuddy-33948.firebasestorage.app',
    iosBundleId: 'com.client.stockbuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZpLL5ht_HMm5nEB_-i0TXVfn5B_5lJMU',
    appId: '1:896018341442:web:154d1feed88e94f8edd7db',
    messagingSenderId: '896018341442',
    projectId: 'stockbuddy-33948',
    authDomain: 'stockbuddy-33948.firebaseapp.com',
    storageBucket: 'stockbuddy-33948.firebasestorage.app',
    measurementId: 'G-JV6GDXJ1NY',
  );
}
